### ISSUE TITLE
Builders in dependencies

### ISSUE THREAD

**Issue by tombentley** [sundrio/sundrio#104]
I have a `@Buildable`-annotated class that extends `io.fabric8.kubernetes.client.CustomResource` and thus inherits `getMetadata()` and `setMetadata()`. I'd like the generated builder to have `withNewMetadata()` etc methods (using the `ObjectMetaBuilder`, `ObjectMetaFluent` from the fabric8 jar), but these methods do not get generated. I suppose this is because the `@Buildable` has `SOURCE` retention, so the processor cannot know that this class already has a builder, fluent.

I *thought* this is what the `@ExternalBuildables` annotation was for, but the documentation is not exactly clear how this is supposed to work, and my attempts to make it work haven't succeeded.

The closest I've managed to get is by overriding `getMetadata()` and `setMetadata()` on my class, which as least gets me a `withMetadata()` method, but not the `withNewMetadata()` methods.

If this is supposed to be supported via `@ExternalBuildables` then I think it needs better documentation and examples. If not, then is this a feature that could be supported?

**Comment by iocanel** [comment]
@tombentley: This is supported using @BuildableReference. With BuildableReference you are able to let sundrio know about builders that have been defined in external projects. Here's an example: https://github.com/snowdrop/service-catalog-java-api/blob/master/annotator/src/main/java/me/snowdrop/servicecatalog/ServiceCatalogTypeAnnotator.java#L57

I'll keep this open until it gets better documented.

**Comment by tombentley** [comment]
@iocanel thanks. I tried that with one of my classes: https://github.com/strimzi/strimzi-kafka-operator/blob/239166e306f19b507116fab4e028be0abbc49e67/api/src/main/java/io/strimzi/api/kafka/model/KafkaTopic.java#L46

When I add:

```java
@ExternalBuildables(
        refs = {@BuildableReference(ObjectMeta.class)},
        builderPackage = "io.strimzi.api.kafka.model",
        generateBuilderPackage = true,
        editableEnabled = false
)
```

it compiles OK, but:

* I get a `io.fabric8.kubernetes.api.model` package in my `generated-sources` dir. I was under the impression it would simply not generate those and let me use the one from fabrics-kubernetes.api.jar on the classpath. If I try different values for `builderPackage` or `generateBuilderPackage` the processor gives me errors.
* the generated `KafkaTopicBuilder` still lacks a `withNewMetadata()` method (it has `withMetadata()`)

**Comment by iocanel** [comment]
@tombentley: how about setting generateBuilderPakcage = false ?

**Comment by tombentley** [comment]
@iocanel 

Changing all the `generateBuilderPackage` to false and also pointing the `builderPackage` at the fabric8 one (since that's the dependency), in other words:

```
@Buildable(
        editableEnabled = false,
        generateBuilderPackage = false,
        builderPackage = "io.fabric8.kubernetes.api.builder"
)
@ExternalBuildables(
        refs = {@BuildableReference(ObjectMeta.class)},
        builderPackage = "io.fabric8.kubernetes.api.builder",
        generateBuilderPackage = false,
        editableEnabled = false
)
```

then it compiles, but I still end up with `ObjectMetaBuilder` etc classes in `io.fabric8.kubernetes.api.model` package and still no `withNewMetadata()`. (And to get `withMetadata()` I have to override `getMetadata()` on the POJO)

**Comment by tombentley** [comment]
That almost all works, thanks @iocanel. I had misunderstood/overlooked that you can have refs on the `@Buildable`. 

The one place I still have problems is a class with a property of type `Affinity` (from the fabric8 API). If I include `refs = { @BuildableReference(io.fabric8.kubernetes.api.model.Affinity.class) }` on the `@Buildable` for that class then an `AffinityBuilder` is generated in `io.fabric8.kubernetes.api.model` masking the fabric8 one. But because I'm not using editors the generated one is not API compatible. Really I just want to reuse the existing fabric8 classes, and not generate any `io.fabric8.kubernetes.api.model` package.

**Comment by tombentley** [comment]
Oh, and another minor problem is that even though my CRD classes extends `CustomResource` (hence in inherit a metadata property) the generator doesn't generate `withMetadata()`. I have to add an unused `private ObjectMeta metadata;` field to my class. This can't be how it's supposed to work, right?

**Comment by iocanel** [comment]
@tombentley: you should do the same trick you did with `ObjectMeta`. Just add a @BuildableReference to CustomResource.

Now, if you still get classes generated under io.fabric8.kubernetes.api.model, please make sure that `generateBuilderPackage` is set to false *everywhere*.

**Comment by tombentley** [comment]
@iocanel yeah, I tried adding ` @BuildableReference` and no combination that I've tried works:

* `editableEnabled = true, generateBuilderPackage = false` ⇒ Compiler errors in my Fluents and Builders: cannot find symbol Fluent, BaseFluent, Editable etc.
* `editableEnabled = false, generateBuilderPackage = false` ⇒ ditto
* `editableEnabled = true, generateBuilderPackage = true` ⇒ cannot find symbol method editOrNewPodAntiAffinity(), location: variable builder of type io.fabric8.kubernetes.api.model.AffinityBuilder (this is the generated one which I don't want)
* `editableEnabled = false, generateBuilderPackage = true` ⇒ ditto

I can get a little further if I add a `@BuildableReference(io.fabric8.kubernetes.api.model.PodAntiAffinity.class)` (it falls over with missing method symbol `addNewPreferredDuringSchedulingIgnoredDuringExecution()`), but since my class doesn't directly use the PodAntiAffinity class this shouldn't be necessary.

**Comment by bfink13** [comment]
@tombentley I'm running into this same issue - did you find a solution?

**Comment by tombentley** [comment]
@bfink13 no. The workaround we currently use is to annotate with

```java
@Buildable(
        editableEnabled = false,
        generateBuilderPackage = false,
        builderPackage = "io.fabric8.kubernetes.api.builder",
        inline = @Inline(type = Doneable.class, prefix = "Doneable", value = "done")
)
```

add a completely pointless `private ObjectMeta metadata;` field to the class and to use overloads:

```java
    @Override
    public ObjectMeta getMetadata() {
        return super.getMetadata();
    }

    @Override
    public void setMetadata(ObjectMeta metadata) {
        super.setMetadata(metadata);
    }
```

That makes the generated Builders workable, but is obviously not ideal.

**Comment by bfink13** [comment]
I'll add one more thing - I'm also seeing the issue with the generated `io.fabric8.kubernetes.api.model` classes clobbering the official classes. @iocanel I tried adding `generateBuilderPackage=false` everywhere and it didn't work (also, `false` is the default).

Any other ideas on this? For now I'm going to just try generating builders for classes that I own.

**Comment by iocanel** [comment]
@tombentley @bfink13: As of https://github.com/sundrio/sundrio/commit/1757f8141e1c65631ae5cd721656e45f6d347b63
The package `io.fabric8.kubernetes.api.model` should not longer be generated.

So, the remaining issue is to correctly handle properties found in the superclass, right?

**Comment by tombentley** [comment]
Yes, I think so

**Comment by bfink13** [comment]
Sorry, I think I had missed something yesterday. I agree, superclass properties are the only thing missing now.

**Comment by iocanel** [comment]
@tombentley, @bfink13: The generated fluent and impl classeses are meant to extends the fluent and impl of the superclass. In your case this means that the generated code shouldn't contain withMetadata() but should inherit that instead. Isn't that the case?

**Comment by tombentley** [comment]
I have:

* `public class Kafka extends CustomResource`
* `public interface KafkaFluent<A extends KafkaFluent<A>> extends Fluent<A>` 
* `public class KafkaFluentImpl<A extends KafkaFluent<A>> extends io.fabric8.kubernetes.api.builder.BaseFluent<A> implements KafkaFluent<A>`

`CustomResource` is the one from fabric8 and has `public abstract class CustomResource implements HasMetadata`, but it doesn't have a `Builder`/`Fluent` etc. So maybe that's the problem?

**Comment by iocanel** [comment]
Yeah! I would make that Buildable.

**Comment by bfink13** [comment]
"that" being `CustomResource`?

**Comment by iocanel** [comment]
Yeah

**Comment by tombentley** [comment]
_I_ can't make it buildable, since it's declared in a dependency (`io.fabric8:kubernetes-client`). The question is why fabric8 doesn't declare it buildable.

**Comment by iocanel** [comment]
Right! We need to fix it there (kubernetes-client).

**Comment by bfink13** [comment]
`CustomResource` is abstract - I remember seeing an issue or commits saying we can't generate builders for abstract classes :/

**Comment by iocanel** [comment]
Builders will not be generated, but fluent interfaces will and that's all
we need.

**Comment by bfink13** [comment]
I'm going to submit a PR to make `CustomResource` buildable with https://github.com/bfink13/kubernetes-client/commit/d2db0dbfc4c77cd1c453a394258c894a35b6ba0e.

However, after testing that locally, I'm still seeing the issue of my project generating `io.fabric8.kubernetes.client`. I feel like I'm missing something obvious :( Here is my `@Buildable` annotation:
```
@Buildable(
        builderPackage = "io.fabric8.kubernetes.api.builder",
        inline = @Inline(type = Doneable.class, prefix = "Doneable", value = "done"),
        editableEnabled = false,
        generateBuilderPackage = false,
        refs = @BuildableReference(io.fabric8.kubernetes.client.CustomResource.class)
)
```

The generated code looks good, it's just that I'm getting generated `CustomResourceFluent` and `CustomResourceFluentImpl` classes. I've set `generateBuilderPackage = false` on every `@Buildable` in my project.

Thoughts?

**Comment by iocanel** [comment]
The `CustomResourceFluentIml` and `CustomResourceFluent` should only exist in one jar.

Sundrio, is meant to skip the generation of a class that is already present in the classpath.

So, if they are generated as part of the client build, they shouldn't be generated in your project too. Note: this is a recent change so, make sure you have one of the latest versions.

**Comment by bfink13** [comment]
It definitely seems like it should be working. I'm using Gradle to build and I think something weird is going on with the classpath (or something along those lines)...

**Comment by bfink13** [comment]
https://github.com/fabric8io/kubernetes-client/pull/1346 was merged so this should be good to go.

**Comment by iocanel** [comment]
I think we could close this. Please re-open if anything additonal needs to be done.
