### ISSUE TITLE
Builder doesn't support code with `$` in the name...

### ISSUE THREAD

**Issue by brendandburns** [sundrio/sundrio#125]
I have methods named `set$Schema` and `set$Ref` (don't ask, code generation ftw...)

and sundrio builder generation drops the `$` character (and thus the builder's don't compile...

**Comment by iocanel** [comment]
@brendandburns: It's almost impossible to get the  `$` handled in a way that satisfies everyone. I'll need to have a look and see if there is a way to have it configurable.
