### ISSUE TITLE
Version 1.14.0 ?

### ISSUE THREAD

**Issue by tombentley** [sundrio/sundrio#126]
According to https://search.maven.org/artifact/io.sundr/builder-annotations/1.14.0/jar there's a version 1.14.0, but it doesn't really exist because https://repo1.maven.org/maven2/io/sundr/builder-annotations/1.14.0/ gives 404.

What happened to 1.14.0 and is 0.15.1 the most recent version?

**Comment by iocanel** [comment]
The 1.14.0 was accidentally released instead of 0.14.0. 

The artifacts have been removed from maven central, and I think that they shouldn't appear in search.maven.org.

**Comment by iocanel** [comment]
I would trust the badge listed on the main github page when it comes to the latest release.

**Comment by iocanel** [comment]
Crap, that's not accurate either.

**Comment by iocanel** [comment]
Nothing to do here, badge currently shows the correct version and artifacts have been removed from central
