### ISSUE TITLE
Pluralize should be able to handle words which are already plural

### ISSUE THREAD

**Issue by rohanKanojia** [sundrio/sundrio#127]
We're facing an issue in kubernetes client: https://github.com/fabric8io/kubernetes-client/issues/1359 where pluralize is unable to handle class name which is already plural, in my opinion it should be smart enough to detect if it's already plural and return plain name without any transformation.

### How to test:
Simply add this test in PluralizeTest:
```
    @Test
    public void testPluralize() {
        assertEquals("endpoints", Pluralize.FUNCTION.apply("endpoints"));
    }
```
Sundrio version: 0.14.6

**Comment by candyleer** [comment]
Hope fix as soon as possible
