### ISSUE TITLE
NPE when using byte[] as type

### ISSUE THREAD

**Issue by ctron** [sundrio/sundrio#133]
Having a type of `byte[]` causes the builders to generate invalid code, throwing a NPE:

~~~java
    public A withCertificate(byte... certificate){
            if (this.certificate != null) {this.certificate.clear();}
            if (certificate != null) {for (byte item :certificate){ this.addToCertificate(item);}} return (A) this;
    }

    public A addToCertificate(Byte... items){
            if (this.certificate == null) {this.certificate = null;}
            for (Byte item : items) {this.certificate.add(item);} return (A)this;
    }
~~~

I would also suggest to use `addAll` instead of manually iterating over the list of items.

**Comment by iocanel** [comment]
@ctron can you please profile more information on how this results in NPE?

**Comment by ctron** [comment]
Simple Assume `this.certificate` is `null` … then the call to `this.certificate.add(…)` will cause a NPE.

**Comment by iocanel** [comment]
@ctron Thanks, I will look into it.
