### ISSUE TITLE
Improper equals implementation

### ISSUE THREAD

**Issue by metacosm** [sundrio/sundrio#142]
Generated `equals` methods start with the following code:
```
if (this == o) return true;
if (o == null || getClass() != o.getClass()) return false;
if (!super.equals(o)) return false;
```
which is fine, until `super` is `Object`, in which case `super.equals(o)` will fail each time we're not comparing with the same (as is identical) object. Check for `super` equality should probably happen at the end, after we've checked for more specific fields first.

**Comment by naitikdani** [comment]
@metacosm / @iocanel  do we have an estimate about when this bug will be fixed.

**Comment by metacosm** [comment]
@naitikdani this issue is fixed actually. We wanted to add more improvements to make it easier to remove matching objects.
