### ISSUE TITLE
Generated Getter method name for "Boolean" fields violates JavaBean conventions

### ISSUE THREAD

**Issue by yue9944882** [sundrio/sundrio#151]
xref: https://github.com/kubernetes-client/java/issues/592

Boolean is not a primitive type, so `getFoo()` getter is required instead of `isFoo()` to align w/ broader usages.

https://stackoverflow.com/questions/10188686/is-public-boolean-isbiketyreflat-a-valid-javabeans-method-signature/10188755#10188755

https://github.com/sundrio/sundrio/blob/789621887eff9f5ecf5d5942bf262eeb176be79a/codegen/src/main/java/io/sundr/codegen/utils/TypeUtils.java#L318

**Comment by iocanel** [comment]
As of sundrio 0.40.0 this has been addressed.
