### ISSUE TITLE
NPEs and `withNew*(String)`

### ISSUE THREAD

**Issue by tombentley** [sundrio/sundrio#152]
The `withNew*(String)` methods generated for String-typed properties will make a copy of the string parameter. This means `withNewFoo(null)` will throw an NPE whereas `withFoo(null)` is safe with nulls. This is a bit of a trap for programmers who use `withNewFoo()` by mistake. Should `withNew*(String)` by made to tolerate a null argument?

Why do we even generate `withNew*()` for String-typed properties? It seems pointless, since String is immutable.

**Comment by iocanel** [comment]
Agree! 

There is no point in generating withNew for non-complex or non-buildable Objects.
I think that this was a regression that was resolved recently. What version are you using @tombentley ?

**Comment by tombentley** [comment]
0.16.5. Hoping to upgrade, but because of #150 that's not completely trivial.

**Comment by iocanel** [comment]
Ok, makes sense!

**Comment by tombentley** [comment]
FYI upgraded today to 0.19.0 and the `withNew*(String)` methods still seem to be generated.

**Comment by iocanel** [comment]
Will have a closer look.

**Comment by iocanel** [comment]
@tombentley I don't see any `withNew` on non-buildable objects.
Please not that for objects with small number of primitive and String properties  (below 5) we do create a `withNew` that inlines all arguments. So if you have objects that just wrap a single String property you will still see `withNew*(String)` and thats expected.

The question is:
- does what you see fall into that category? (single string wrapper)?
- do you get NPE for that case?
- can you provide a reproducer?

**Comment by tombentley** [comment]
We're observing this happening on a class with 5 string properties. If you meant ≤5 rather than <5 properties then this would fit with what you're saying. Out of interest what's the rationale for this special case?

In any case why is the generated code:

    public A withNewMessage(String arg1){
            return (A)withMessage(new String(arg1));
    }

and not

    public A withNewMessage(String arg1){
            return (A)withMessage(arg1);
    }

which would avoid the NPE which was how I originally discovered this. I guess it's by symmetry with the StringBuilder and StringBuffer methods, in which case why not just generate

    public A withNewMessage(CharSequence arg1){
            return (A)withMessage(arg1 != null ? arg1.toString() : null);
    }

and avoid those overloads entirely?

**Comment by iocanel** [comment]
@tombentley:  I am not sure why these methods are generated this way, but I agree it doesn't look correct. I'll fix that asap.
