### ISSUE TITLE
Tips to override Velocity's log chute?

### ISSUE THREAD

**Issue by xguerin** [sundrio/sundrio#154]
Hello,

I apologize in advance for the seemingly peripheral topic but I am reaching my rope's end.

I am using the Fabric8 Kubernetes client. It uses your library internally.

I have been trying to get rid of the `velocity.log` file that is created during compilation (I am using maven). I was a able to track it down to the `BuildableProcessor` class, but I cannot for the life of me figure out a way to disable it.

I've tried to place a `velocity.properties` file in my resources but since it seems to happen at compile time it does not seem to work.

Thanks for any help you could provide.

**Comment by iocanel** [comment]
@xguerin: I am surprised to hear you are getting a velocity.log on many levels:

1. The kubernetes-client has an optional compile scoped dependency on sundrio.
2. Even if sundrio ends up in your compile path it still shouldn't be triggered unless you have sources with sundrio annotations e.g. `@Buildable`.
3. I haven't seen a velocity.log in the many projects I've been toying with sundrio  (even when I needed too).

So, I am starting to think that maybe in your case its generated by something else.
Is it possible to share your project, velocity.log or anything that could help us identify the issue?

Also, what version of the kubernetes-client and sundrio you have in your classpath?

**Comment by xguerin** [comment]
@iocanel I found out about `sundrio` by forcing velocity to fail creating the log file and check were the creation was initiated (simply by making the log file RO). This is the kind of error I got:

```
Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider io.sundr.builder.internal.processor.BuildableProcessor could not be instantiated: org.apache.velocity.exception.VelocityException: Error initializing log: Failed to initialize an instance of org.apache.velocity.runtime.log.Log4JLogChute with the current runtime configuration
```

I cannot share my project unfortunately.

Here are the versions I am using:
* `kubernetes-client`: 4.1.1
* `builder-annotations`: 0.18.0 (io.fabric8.mockwebserver uses 0.2.7 but is scoped test)

Here is the content of the velocity log: https://gist.github.com/xguerin/15bd3edf075416612bf7bbe0c303b135

**Comment by iocanel** [comment]
@xguerin That's weird. 
Would overriding the log chute via system properties solve your problem?

**Comment by xguerin** [comment]
I'd love to try but whatever information I found about velocity did not mention any way to overriding the chute but through the `velocity.properties` file. Do you have a particular option in mind?

**Comment by iocanel** [comment]
The builder generator is now decoupled from velocity

Also, for module that still do (e.g. transform-annotations) we provide the option to use both shaded and unshaded version of velocity. So, I think that just by using the unshaded version one could solve this issue.
