### ISSUE TITLE
Null values being converted to empty LinkedHashMaps in builder objects

### ISSUE THREAD

**Issue by rohanKanojia** [sundrio/sundrio#159]
Hello,

We're using this project in Fabric8 Kubernetes Client to generate builders classes for Kubernetes resources. I was investigating this bug: https://github.com/fabric8io/kubernetes-client/issues/1486 and I think it might be coming due to a behavior in sundrio.

For CustomResourceDefinition objects, we generate CustomResourceDefinitionBuilder using sundrio. When I try to create a CustomResourceDefinition using the builder object, I notice a slight difference in the created object. This is the code I used for creating CustomResourceDefinition:
```
        try (final KubernetesClient client = new DefaultKubernetesClient()) {
            JSONSchemaProps schema = readSchema();

            CustomResourceDefinitionBuilder builder = new CustomResourceDefinitionBuilder()
                    .withApiVersion("apiextensions.k8s.io/v1beta1")
                    .withNewMetadata().withName("sparkclusters.radanalytics.io")
                    .endMetadata()
                    .withNewSpec()
                    .withNewNames()
                    .withKind("SparkCluster")
                    .withPlural("sparkclusters")
                    .endNames()
                    .withGroup("radanalytics.io")
                    .withVersion("v1")
                    .withScope("Namespaced")
                    .withNewValidation()
                    .withNewOpenAPIV3SchemaLike(schema)
                    .endOpenAPIV3Schema()
                    .endValidation()
                    .endSpec();

            CustomResourceDefinition sparkCrd = builder.build();
            client.customResourceDefinitions().createOrReplace(sparkCrd);
        }
```
`readSchema` method is just reading a json as JsonSchemaProps object. We can see that `dependencies` field is set to null here.
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Test configuration",
  "dependencies": null,
  "type": "object",
  "properties": {
    "spec": {
      "type": "object",
      "properties": {
        "replicas": {
          "type": "integer",
          "minimum": 1
        }
      }
    }
  },
  "required": ["spec"]
}
```
When `schema` object is loaded, I can see `dependencies` being set to null as expected. 
![Screenshot from 2019-10-10 18-53-54](https://user-images.githubusercontent.com/13834498/66573062-aefa4a00-eb8f-11e9-8d20-7f297f90b8e7.png)

Whereas after CustomResourceDefinition is  created from the builder, the resulting object becomes like this, `null` gets converted to `LinkedHashMap`:
![Screenshot from 2019-10-10 18-53-31](https://user-images.githubusercontent.com/13834498/66573156-d81ada80-eb8f-11e9-883f-684a5adafdea.png)

Another thing that I observed is that when I try to `load()` the custom resource from yaml, which simply deserializes yaml into `CustomResourceDefinition` object and then apply; it gets applied properly.  
Is this desired behaviour from sundrio? If yes, is it possible to configure it? Would appreciate if I could get any help in order to resolve this.

**Comment by iocanel** [comment]
@rohanKanojia: At some point we added an option that allows for lazy collection initialization. When enabled (I think its on by default) it will automatically intiallize lists and sets. 

If you don't want this behavior, you need to disable it.

https://github.com/sundrio/sundrio/blob/master/annotations/builder/src/main/java/io/sundr/builder/annotations/Buildable.java#L32
