### ISSUE TITLE
TypeDef creation is non-deterministic resulting in random errors / unpredictable results

### ISSUE THREAD

**Issue by metacosm** [sundrio/sundrio#229]
The outcome of extracting a `TypeDef` from a `Class` or `TypeElement` should be deterministic.

**Comment by iocanel** [comment]
The description is quite generic, but I assume that you are referring to the intermittent failures in the CRD Generator.

While we don't have that many tests, the few we do, do not seem to suffer from neither non-determinism nor from any kind of intermittent failures. Also, lack of determinism has never been spotted around `TypeElement -> TypeDef` which is something that is being massively used by downstream projects, with huge domains (see kubernetes-client).

So, I am wondering if this is something specific to `Class -> TypeDef` or a completely different issue (e.g. tests running in parallel or something along those lines).  

I think that they only way to narrow down this issue, is to move the classes that are causing issues into sundrio itself, and check the conversion / adaptation mechanism in isolation with everything else.

**Comment by iocanel** [comment]
I think this has been long fixed.
