### ISSUE TITLE
Buildable fields in generic parents

### ISSUE THREAD

**Issue by shawkins** [sundrio/sundrio#248]
This is in reference to https://github.com/fabric8io/kubernetes-client/issues/3076 

The CustomResource class holds generic references to the spec and status.  The CustomResourceFluentImpl generated by the project will have default handling for those fields because it's not known at that time if the spec/status classes will be Buildable.

If you then create a MyCustomResource extending CustomResource with spec/status classes that are buildable, there doesn't appear to be a way to override the default behavior - that is a Buildable MyCustomResourceFluentImpl will just defer to CustomResourceFluentImpl for the handling of spec/status.  That result is not desirable, because it is inconsistent with general fabric8 builder behavior that will deep clone the transitive buildable fields.

**Comment by iocanel** [comment]
So the issue is that in this case we miss the nested fluent stuff, right?

That's a little tricky, but I'll have a look.

**Comment by shawkins** [comment]
Right, it will copy by reference rather than via a builder.  That also means you miss out on a lot of fluent methods, you instead have to do ```new MyCustomResourceBuilder().withSpec(new MyCustomResourceSpecBuilder()...```

**Comment by iocanel** [comment]
Unfortunately, the `Generated` annotaiton was introduced in jdk 9.
So, for now we will just add a comment instead.

**Comment by iocanel** [comment]
I will have a look at it ASAP

**Comment by iocanel** [comment]
@shawkins: I created #260 which should provide the desired user experience.

Can you have a look and provide some feedback before I merge/release?

**Comment by shawkins** [comment]
@iocanel thank you.  Yes, I'll pull this locally and try it out.

**Comment by shawkins** [comment]
The generated code looks good.  ConnectionFluentImpl assumes the responsibility of the nested spec.  The only difference with the fabric8 structure is that the base class will be in a different module/package - but I don't think that should matter.

**Comment by iocanel** [comment]
> The generated code looks good. ConnectionFluentImpl assumes the responsibility of the nested spec. The only difference with the fabric8 structure is that the base class will be in a different module/package - but I don't think that should matter.

I don't think that this will be an issue.
