### ISSUE TITLE
Support records

### ISSUE THREAD

**Issue by quintesse** [sundrio/sundrio#259]
The new record type that has been introduced as a preview feature in Java 14 and finalized in Java 16 does not seem to be supported:

```
@Buildable
public record Person(String Name) {}
```

results in:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project main: Fatal error compiling: io.sundr.SundrException: No getter found for property: Name on class: Person -> [Help 1]
```

**Comment by iocanel** [comment]
At the moment, there is no explicit support for `records` in sundrio.
Even though I haven't played with records much I think that they could be treated as regular classes extending `java.lang.Record` and inferring the getters (which seems to be the reason why the builder generator barfed in your case).

I will work on that asap.

**Comment by quintesse** [comment]
Yeah, records don't really have getters, hey are not POJOs. They have methods with the exact same name as the properties. So the `Person` record example I used above would have an implicit `public String Name() { ... }` method.
