### ISSUE TITLE
Eliminate Fluent interface

### ISSUE THREAD

**Issue by iocanel** [sundrio/sundrio#263]
Historically, we separated the `Builder` from the `Fluent`/`FluentImpl` in order to supportthe `Inline` concept: `Being able to use the fluent part of a builder, but with having a different method in the end instead of build. An example of how it was used in the `kubernetes-client`:

```java
Pod pod = client.pods().createNew()
   .withNewSpec()
      .withName("my-pod")
  .endSpec()
  // more code
  .done();
```

It seems though that we don't need both a `Fluent` interface and a `FluentImpl` class.
It might make sense if we collapsed them into one class that will be called `Fluent`.

`Builder` heavy libraries and frameworks could be greatly benefited by the reduced size and the simplified signatures.

**Comment by iocanel** [comment]
FYI: @rohanKanojia @manusa @metacosm

**Comment by metacosm** [comment]
That sounds reasonable to me and any reduction / simplification would be welcome.

**Comment by manusa** [comment]
Sounds good to me. 

I don't think that any dependent project should be directly importing the FluentImpl.

A quick search in GH only revealed this

https://github.com/strimzi/strimzi-kafka-operator/blob/e66ed5c23ba7066984fbcb5050ffde57d0736668/crd-generator/src/main/java/io/strimzi/crdgenerator/CrdGenerator.java#L703

**Comment by iocanel** [comment]
> That sounds reasonable to me and any reduction / simplification would be welcome.
> What would be the impact on the code, more precisely, though? Could you provide more concrete examples of how things would change?

There is no technical reason that forces to have both an interface and a impl for `Fluent` and the truth is that there is only one way to properly implement the `Fluent` interface. So, why have the interface in the first place. It seems like a redundant implementation detail.
