### ISSUE TITLE
builder fails for type containing byte[] field

### ISSUE THREAD

**Issue by davidkarlsen** [sundrio/sundrio#27]
I have a bean/pojo/VO which has a byte[] field.
sundrio creates this code - which does not compile:
```
public byte[] getBlob(){
    List<byte> result = new ArrayList<>();
for (byte item : blob) {
    result.add(item);
}
return result.toArray(new byte[result.size()]);

    }
```

**Comment by iocanel** [comment]
@davidkarlsen: Thanks for reporting.

Can you please provide an example I could use to reproduce?

**Comment by davidkarlsen** [comment]
here you go: https://github.com/davidkarlsen/sundrtest

**Comment by iocanel** [comment]
@davidkarlsen: You are awesome! Thanks!

**Comment by iocanel** [comment]
Pushed a fix and kicked a release. Release 0.2.3 should be in central in a couple of minutes.

**Comment by davidkarlsen** [comment]
You are ultra-awesome :)
