### ISSUE TITLE
Problem getting inheritance to work

### ISSUE THREAD

**Issue by davidkarlsen** [sundrio/sundrio#29]
Have a look at  https://github.com/davidkarlsen/sundrtest (now updated).
I have some abstract beans I extend to inherit properties - but the fluent part will not generate for them - so I slap on @Buildable on the abstract parent bean - but it then generates non-compilable code because it generates two constructors doing instanciation:

```
    public MyAbstractBeanBuilder(){
        this(new MyAbstractBean());
    }
    public MyAbstractBeanBuilder( MyAbstractBeanFluent<?> fluent ){
        this(fluent, new MyAbstractBean());
    }

```

**Comment by iocanel** [comment]
@davidkarlsen: I think that inheritance works fine, but we are trying to generate builders for abstract classes which is conceptually wrong.

I'll fix that asap.

**Comment by iocanel** [comment]
@davidkarlsen: fixed and re-released.
