### ISSUE TITLE
Incompatible types issue with IBM Semeru Runtime

### ISSUE THREAD

**Issue by kun-lu20** [sundrio/sundrio#291]
When compiling codes which use `Sundrio` to generate classes with IBM Semeru Runtime (previously known as AdoptOpenJDK 11 Openj9 JVM), sometimes only `withNew*(byte[])` methods will be generated, while `withNew*(String)` methods are expected in the client code. This will trigger incompatible types compilation error similar to:

```bash
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/test/strimzi-kafka-operator/cluster-operator/src/test/java/io/strimzi/operator/cluster/model/CruiseControlTest.java:[541,47] incompatible types: java.lang.String cannot be converted to byte[]
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
On Temurin runtime (previously known as AdoptOpenJDK 11 Hotspot JVM) and OpenJDK11, `withNew*(String)` methods will be generated and this error would not occur during compilation.

It looks like the root cause might lie in here: https://github.com/sundrio/sundrio/blob/533e4b9b6ecc6ed2c9580c20162d296378e7a6f0/annotations/builder/src/main/java/io/sundr/builder/internal/utils/BuilderUtils.java#L312
The code just chooses the first constructor which has only one argument. Probably on IBM Semeru runtime the `String(byte[])` constructor comes first.

Could anyone please look into this issue and help to fix it? Thanks!

**Comment by iocanel** [comment]
Thanks for the detailed explanation, I will look into it asap.

**Comment by kun-lu20** [comment]
Thanks @iocanel

**Comment by iocanel** [comment]
@kun-lu20: While I wan't able to reproduce thte issue, the code could be simplified and be more deterministic. 
I'll mere #292 and release shortly.

**Comment by kun-lu20** [comment]
@iocanel Thank you so much!
