### ISSUE TITLE
[Question] : How to make `@Buildable` generate builder methods only for specific fields of a class ?

### ISSUE THREAD

**Issue by rohanKanojia** [sundrio/sundrio#298]
I'm working on https://github.com/fabric8io/kubernetes-client/pull/3806 

We're using Sundrio in Fabric8 Kubernetes Client Model. We have a class [`IntOrString`](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/IntOrString.java#L61) ; We want to hide write access to `kind` field from end-users. 

Sundrio generates its builder IntOrStringBuilder. I'm trying to remove the[`.withKind(Integer)`](https://github.com/rohanKanojia/kubernetes-client/blob/pr/intorstring-refactor/kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/IntOrStringTest.java#L107) method from the builder. As per [documentation](https://github.com/sundrio/sundrio/blob/main/annotations/builder/readme.md#generating-builders), builder seems to be generated by constructor arguments:
> On any POJO you can add the @Buildable annotation on a single constructor. On compile time a builder will get generated that will contain methods for all of the constructor arguments. 

I modified the constructor to remove `kind` argument like [this](https://github.com/rohanKanojia/kubernetes-client/blob/pr/intorstring-refactor/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/IntOrString.java#L74):
```java
  @Buildable(editableEnabled = false, generateBuilderPackage=true, builderPackage = "io.fabric8.kubernetes.api.builder")
  public IntOrString(Integer intVal, String strVal, Map<String, Object> additionalProperties) {
      // ...
  }
```

But somehow I'm still seeing the `.withKind(Integer)` builder argument in the generated builder (See [IntOrStringTest](https://github.com/rohanKanojia/kubernetes-client/blob/pr/intorstring-refactor/kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/IntOrStringTest.java#L83) ). 

I'm not sure if this is a bug or some misconfiguration from my side. Would appreciate some help with this.

**Comment by iocanel** [comment]
The steps you followed seem right. So, I'd say it looks like a bug. I'll look into it.
