### ISSUE TITLE
maven-plugin: lost dependencies, messed plugin and dependencies version

### ISSUE THREAD

**Issue by radio-rogal** [sundrio/sundrio#308]
Just copy error messages:

> [ERROR] Failed to execute goal io.sundr:sundr-maven-plugin:0.50.4:generate-bom (default) on project parent: Execution default of goal io.sundr:sundr-maven-plugin:0.50.4:generate-bom failed: Plugin io.sundr:sundr-maven-plugin:0.50.4 or one of its dependencies could not be resolved: Could not find artifact **io.sundr:sundr-codegen:jar:0.50.4** in central (https://repo.maven.apache.org/maven2)

> [ERROR] Failed to execute goal io.sundr:sundr-maven-plugin:0.80.1:generate-bom (default) on project parent: Execution default of goal io.sundr:sundr-maven-plugin:0.80.1:generate-bom failed: Plugin **io.sundr:sundr-maven-plugin:0.80.1** or one of its dependencies could not be resolved: **io.sundr:sundr-codegen:jar:0.80.1** was not found in https://repo.maven.apache.org

But last version of the `codegen` artifact is **0.40.1**.

**Comment by iocanel** [comment]
@radio-rogal: io.sundr:sundr-codegen:jar has been split into several modules, so it no longer exists. I also don't see it being referenced anywhere in the source code.

A reproducer or even the output of mvn dependency:tree could help troubleshooting this.

**Comment by radio-rogal** [comment]
Sorry, it was my fault: the old version 0.40.1 has direct dependencies to codegen and I didn't remove it when increase version.

:(

**Comment by iocanel** [comment]
> Sorry, it was my fault: the old version 0.40.1 has direct dependencies to codegen and I didn't remove it when increase version.
> 
> :(

No worries! I am just happy, we found the root cause of it.
