### ISSUE TITLE
values are not added to instance

### ISSUE THREAD

**Issue by davidkarlsen** [sundrio/sundrio#31]
Please see updated master branch: https://github.com/davidkarlsen/sundrtest - should the test not pass?

**Comment by iocanel** [comment]
@davidkarlsen: There are 2 issues with your tests:

i) Your classes contain no constructors (builders pass values to the target object via constructor, properties which are not reflected in the constructor arguments are ignored).

ii) You are comparing arrays with equals.

**Comment by iocanel** [comment]
I am wondering if we should completely ignore those properties, or if we should just log a warning.

**Comment by iocanel** [comment]
Well, I decided that if there is a setter for the property we should use the setter. 
If neither constructor argument nor setter is found the property will be ignored.

**Comment by iocanel** [comment]
release on its way to central

**Comment by iocanel** [comment]
There are still a few hiccups that need to be addressed.

**Comment by iocanel** [comment]
it should be fine now
