### ISSUE TITLE
Buildable annotation produces invalid code on `Set`s

### ISSUE THREAD

**Issue by andreaTP** [sundrio/sundrio#316]
When a field of a class annotated with the `Buildable` annotation is a `Set` invalid code gets emitted.

Reproduction:
 - change [this type](https://github.com/sundrio/sundrio/blob/c864db8c7cdc3b8c2e9a51a87b8c2e1f2099a695/examples/builder/hello-nested/src/main/java/io/sundr/examples/Family.java#L29) from `List` -> `Set`
 - the sub-module doesn't compile anymore
 
 ```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project builder-hello-nested-example: Compilation failure: Compilation failure: 
[ERROR] /Users/aperuffo/workspace/sundrio/examples/builder/hello-nested/target/generated-sources/annotations/io/sundr/examples/FamilyFluentImpl.java:[141,36] incompatible types: bad type in conditional expression
[ERROR]     no instance(s) of type variable(s) T exist so that java.util.List<T> conforms to java.util.Set<io.sundr.examples.Person>
[ERROR] /Users/aperuffo/workspace/sundrio/examples/builder/hello-nested/target/generated-sources/annotations/io/sundr/examples/FamilyFluentImpl.java:[144,36] incompatible types: bad type in conditional expression
[ERROR]     no instance(s) of type variable(s) T exist so that java.util.List<T> conforms to java.util.Set<io.sundr.examples.Person>
 ```
 
 The problem has been found [here](https://github.com/keycloak/keycloak/blob/0f93f77185f29ecba1e9b41bd7eed8eff8ebfdae/operator/src/main/java/org/keycloak/operator/v2alpha1/crds/KeycloakSpec.java#L32)

**Comment by iocanel** [comment]
I will have a look during the weekend and release soon.
