### ISSUE TITLE
Builder Annotations 1.14.0 is published to maven, is empty, and is considered "latest" version

### ISSUE THREAD

**Issue by sgmorrison** [sundrio/sundrio#327]
I am picking up https://mvnrepository.com/artifact/io.sundr/builder-annotations as a transitive dependency in a Maven project. The project I depend on asks for the "latest" version of this package. This resolves to https://mvnrepository.com/artifact/io.sundr/builder-annotations/1.14.0, published in 2018 and likely a version number typo.

Can we have this version removed from the Maven repo?

Project we get the transitive dependency from: https://mvnrepository.com/artifact/io.fabric8/kubernetes-client/5.9.0

**Comment by iocanel** [comment]
We requested the deletion of the artifacts, however according to this: https://issues.sonatype.org/browse/MVNCENTRAL-4142 this only conver central and the artifact may be still listed in mvnrepository etc. Unfortunately, there is not much we can do.
