### ISSUE TITLE
Getting warnings while maven compile when using crd-generator-apt dependency 

### ISSUE THREAD

**Issue by prateekkohli21** [sundrio/sundrio#351]
I am getting the below warnings when I am adding crd-generator-apt dependency to my pom:
crd-generator-apt is getting sundr jars with 0.92.1 version.

[WARNING] No SupportedSourceVersion annotation found on io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor' less than -source '11'
[WARNING] No SupportedSourceVersion annotation found on io.sundr.resourcecify.internal.processor.ResourcecifyProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.sundr.resourcecify.internal.processor.ResourcecifyProcessor' less than -source '11'
[INFO] 4 warnings
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] No SupportedSourceVersion annotation found on io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor' less than -source '11'
[WARNING] No SupportedSourceVersion annotation found on io.sundr.resourcecify.internal.processor.ResourcecifyProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.sundr.resourcecify.internal.processor.ResourcecifyProcessor' less than -source '11'
[INFO] 4 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] warnings found and -Werror specified
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.997 s
[INFO] Finished at: 2022-11-22T12:31:12+05:30

Attaching the pom file for your reference.

[pom.txt](https://github.com/sundrio/sundrio/files/10068314/pom.txt)

**Comment by iocanel** [comment]
As far as sundrio is concerned the warnings have been addressed as of https://github.com/sundrio/sundrio/commit/c0f1740ea15ba66cfb491626b8188e008d4e1280. 

The same technique should be applied to the crd generator to see the issue completely gone. Nothing else needs to be done on the sundrio side of things, so I think we can close this one.
