### ISSUE TITLE
Breaking changes for 0.100.0 release

### ISSUE THREAD

**Issue by shawkins** [sundrio/sundrio#384]
Just wanted to catalog some possible breaking changes for 0.100.0, which may be eventually moved into the readme.md

* remove deprecated getXXX methods, which should use buildXXX instead
* from #379 removal of methods that reference a concrete descendant type that remove/add/removeMatching from a collection or use with.  Instead a general method should be used - removeAllFromCollection(SuperType... value).  This will be a hard breaking change in that the methods will not have been previously deprecated, which may mean downstream projects may want to avoid this version change in a fix release.

**Comment by shawkins** [comment]
@iocanel is there anywhere else you want this captured?

**Comment by iocanel** [comment]
> @iocanel is there anywhere else you want this captured?
Don't have something to add.

**Comment by shawkins** [comment]
Marking as resolved.  Added a changelog based upon this for https://github.com/fabric8io/kubernetes-client/pull/5308
