### ISSUE TITLE
Buildable unable to use lombok.AllArgsConstructor and lombok.Getter

### ISSUE THREAD

**Issue by nlippis** [sundrio/sundrio#390]
Buildable cannot use the class constructor generated by lombok.AllArgsConstructor and the getters generated by lombok.Getter.  Is this a defect or a known/desired limitation?

**When a class's constructor is generated by lombok**
The builders are generated, however they are `empty` meaning that none of the class's fields have corresponding `with{Field}` setter on the classes builder.

**When a class's constructor is not generated by lombok but it's getters are generated by lombok**
The builders are generated with all corresponding `with{Field}` setters, however setting fields on nested class's returns an object with all empty values (note that the top level object has it's values properly set).

E.G
Family.java
```
@Getter
@Buildable
public class Family {

  @JsonProperty
  Person father;
  
  @JsonProperty
  Person mother;
 
  @JsonProperty
  List<Person> children;

  public Family(Person father, Person mother, List<Person> children) {
    this.father = father;
    this.mother = mother;
    this.children = children;
  }
}
```

Person.java
```
@Getter
@Buildable
public class Person {

  @JsonProperty
  private final String firstName;
  
  @JsonProperty
  private final String lastName;

  public Person(String firstName, String lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
  }
}
```

Hello.java
```
public class Hello {

  public static void main(String[] args) {
    Family family = new FamilyBuilder()
      .withNewFather()
        .withFirstName("John")
        .withLastName("Doe")
      .endFather()
      .withNewMother()
        .withFirstName("Jane")
        .withLastName("Doe")
      .endMother()
      .addNewChild()
      .withFirstName("Jimmy")
      .withLastName("Doe")
      .endChild()
      .build();

    ObjectMapper mapper = new ObjectMapper();
      
    System.out.println(mapper.writeValueAsString(family));
  }
}
```

Will print the following
```
{
    "father": {
        "firstName": null,
        "lastName": null
    },
    "mother": {
        "firstName": null,
        "lastName": null
    }
    "children": [
        {
             "firstName": null,
             "lastName": null
        }
    ]
}
```

**Comment by iocanel** [comment]
*Short answer*: Not directly supported but there is a workaround.

*Long answer*: As is the case with all annotaton processors, they act uppon the compiled source (which in your doesn't have getters and all arg constructor). Unless we add special handling for lobmok (which is something we should probably do) there is no way for us to use these methods.

*Workaround*: We also have `@ExternalBuildables` which is `@Buildable` for external classes. `@ExternalBuidlables` will use the class and not the source so, it will be able to pickup methods / constructors added by lombok. 

See the example: https://github.com/kubernetes-client/java/blob/master/fluent-gen/src/main/java/io/kubernetes/client/fluent/Config.java


*Implementation ideas*: We should create vistiors that creates setters and all arg constructors and apply them to all lombok annotated types.
