### ISSUE TITLE
Fluent Builder code generation issue

### ISSUE THREAD

**Issue by ryantse** [sundrio/sundrio#407]
When an object has the following class definition:

```
public class IstioDestinationRule implements KubernetesResource
{

    @JsonProperty("canarySubsetName")
    private String canarySubsetName;
    @JsonProperty("name")
    private String name;
    @JsonProperty("stableSubsetName")
    private String stableSubsetName;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    @JsonProperty("canarySubsetName")
    public String getCanarySubsetName() {
        return canarySubsetName;
    }

    @JsonProperty("canarySubsetName")
    public void setCanarySubsetName(String canarySubsetName) {
        this.canarySubsetName = canarySubsetName;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }
```

When using the Fluent builder annotation processing, there exists an issue with matching the correct setter function when calling `Setter.find` here: https://github.com/sundrio/sundrio/blob/main/annotations/builder/src/main/java/io/sundr/builder/internal/functions/ClazzAs.java#L679

Due to the way the `Setter.find` logic works, the property `name` gets matched with `setCanarySubsetName` since the function ends with `setName`.

**Comment by ryantse** [comment]
@iocanel: Appreciate you merging my patch! I'm wondering when this might land in a release. Is there a regular release cadence for this project? This issue is completely breaking my use case with the fabric8 Kubernetes-client and I'd really appreciate if this can be fixed in a release ASAP.

**Comment by iocanel** [comment]
> @iocanel: Appreciate you merging my patch! I'm wondering when this might land in a release. Is there a regular release cadence for this project? 
No, we release whenever there's need.
I'll kick a release later today.
