### ISSUE TITLE
[Builder Annotation] : Problems in generating fluent builder when member fields have same type names

### ISSUE THREAD

**Issue by rohanKanojia** [sundrio/sundrio#425]
## Description
I'm trying to bump OpenShift Model as part of https://github.com/fabric8io/kubernetes-client/issues/5286

I'm facing an issue with sundrio when it's generating a builder for this Pojo : [openshift/hive/apis/hive/v1/clusterdeployment_types.go](https://github.com/openshift/hive/blob/master/apis/hive/v1/clusterdeployment_types.go#L309-L317) . It seems to contain two fields which seem to have same type names but actually they're coming from different packages. When I compile project it fails with this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project openshift-model-hive: Compilation failure
incompatible types: io.fabric8.openshift.api.model.hive.aws.v1.Metadata cannot be converted to io.fabric8.openshift.api.model.hive.azure.v1.Metadata
```

If I add [a hack in go script](https://github.com/rohanKanojia/kubernetes-client/blob/pr/issue5286/kubernetes-model-generator/openshift-model-hive/cmd/generate/generate.go#L136-L141) in go script to modify  kube-schema.json file to rename class names to AwsMetadata and AzureMetadata, the project builds successfully.

Is there some configuration option to avoid this name collision? Could this be a bug in sundrio?

## How to Reproduce?
1. Download this reproducer project [sundrio-builder-issue-reproducer.zip](https://github.com/sundrio/sundrio/files/12769633/sundrio-builder-issue-reproducer.zip)
2. Run `mvn clean install`, you'd see the error mentioned in issue description

**Comment by iocanel** [comment]
There is no direct way to address this issue. This was supposed to work, but apparently we have a regression.

**Comment by rohanKanojia** [comment]
No problem, I was able to proceed forward by adding a hack in go generate script.

**Comment by shawkins** [comment]
I've seen something similar before, and added a narrow workaround in the generation logic.  There's some logic that runs after most of the transformations that will strip qualification from things that are in the same package - it does not understand if that quarlification is needed.

**Comment by rohanKanojia** [comment]
I upgraded to newer sundrio version and I can no longer see the error. Thanks.

However, I see some additional changes in builder methods which I did not expect:
```diff
--- a/kubernetes-model-generator/openshift-model-hive/src/test/java/io/fabric8/openshift/api/model/hive/v1/ClusterPoolTest.java
+++ b/kubernetes-model-generator/openshift-model-hive/src/test/java/io/fabric8/openshift/api/model/hive/v1/ClusterPoolTest.java
@@ -67,12 +67,12 @@ class ClusterPoolTest {
         .withName("openshift-4-6")
         .endImageSetRef()
         .withNewPlatform()
-        .withNewAws()
+        .withNewAwsAws()
         .withNewCredentialsSecretRef()
         .withName("hive-team-aws-creds")
         .endCredentialsSecretRef()
         .withRegion("us-east-1")
-        .endAws()
+        .endAwsAws()
         .endPlatform()
         .withNewPullSecretRef()
         .withName("hive-team-pull-secret")
```

Shall I create a new issue about this?

**Comment by shawkins** [comment]
> Shall I create a new issue about this?

Yes that warrants an issue.
