### ISSUE TITLE
Request to delete `master` branch

### ISSUE THREAD

**Issue by rohanKanojia** [sundrio/sundrio#458]
I noticed that the project has switched to `main` branch from `master`. Initially, I got confused as I still had `master` branch in my cloned version, and pulling it wasn't updating the project. It would be better to keep just one. However, if it's kept for some specific reason it's fine as it is.

**Comment by shawkins** [comment]
@rohanKanojia master no longer seems to be in the upstream. It should be safe to delete from your clone.

**Comment by rohanKanojia** [comment]
@shawkins : Thanks a lot!
