### ISSUE TITLE
make generated codes happy on Virtual Threads

### ISSUE THREAD

**Issue by xiaoma20082008** [sundrio/sundrio#460]
Now all generated codes are using `synchronized` keyword, As [JEP 444: Virtual Threads](https://openjdk.org/jeps/444) has released in jdk21, maybe the generated codes should use `java.util.concurrent.locks.Lock` instead of `synchronized` to make `VirtualThread` happy.

**Comment by shawkins** [comment]
@xiaoma20082008 what generated code are your referring to? Do you have a diagnostic run that shows an issue from synchronzied usage within sundrio? Also there should not be anything blocking that sundrio is doing while holding a lock.

**Comment by shawkins** [comment]
Closing due to lack of feedback
