### ISSUE TITLE
Help needed to compile with jdk17

### ISSUE THREAD

**Issue by rashiq-ahmd** [sundrio/sundrio#461]
Hi team i need help to compil;e this with jdk17

`Failed to execute goal on project sundr-adapter-api: Could not resolve dependencies for project io.sundr:sundr-adapter-api:jar:999-SNAPSHOT: The following artifacts could not be resolved: io.sundr:sundr-model:jar:999-SNAPSHOT, io.sundr:sundr-model-utils:jar:999-SNAPSHOT: Could not find artifact io.sundr:sundr-model:jar:999-SNAPSHOT -> [Help 1]`

added tools jar manually, and got this error

`[ERROR] Failed to execute goal net.revelc.code:impsort-maven-plugin:1.4.1:sort (default) on project sundr-core: Execution default of goal net.revelc.code:impsort-maven-plugin:1.4.1:sort failed: A required class was missing while executing net.revelc.code:impsort-maven-plugin:1.4.1:sort: org/codehaus/plexus/util/DirectoryScanner
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.revelc.code:impsort-maven-plugin:1.4.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/rashiq_ahmd/.m2/repository/net/revelc/code/impsort-maven-plugin/1.4.1/impsort-maven-plugin-1.4.1.jar
[ERROR] urls[1] = file:/Users/rashiq_ahmd/.m2/repository/com/github/javaparser/javaparser-core/3.15.21/javaparser-core-3.15.21.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]`

**Comment by iocanel** [comment]
@rashiq-ahmd: It seems like you are trying to build the project from source, yet you haven't build some of the modules (e.g. sundr-model). An `mvn clean install` should work fine. Are you trying something different?

Check our CI jobs, they are building the project using jdk versions 8,11,17 and 21. AFAIR tools.jar is only needed for 8.

**Comment by rashiq-ahmd** [comment]
i'm getting this error while building

`Failed to execute goal on project sundr-adapter-api: Could not resolve dependencies for project io.sundr:sundr-adapter-api:jar:999-SNAPSHOT: The following artifacts could not be resolved: io.sundr:sundr-model:jar:999-SNAPSHOT, io.sundr:sundr-model-utils:jar:999-SNAPSHOT: Could not find artifact io.sundr:sundr-model:jar:999-SNAPSHOT -> [Help 1]`

**Comment by rashiq-ahmd** [comment]
@iocanel , Can you please share me the details About the CI jobs that build using jdk17 ?

**Comment by andreaTP** [comment]
This should be it:
https://github.com/sundrio/sundrio/blob/main/.github%2Fworkflows%2Fbuild.yml#L32

**Comment by rashiq-ahmd** [comment]
Worked, thanks You
