### ISSUE TITLE
Consider not always forcing scopes on dependencies in generated BOMs

### ISSUE THREAD

**Issue by jamesnetherton** [sundrio/sundrio#53]
It may not always be desirable for the Sundr Plugin to explicitly declare scopes on all dependencies. E.g specifying dependencies as 'compile' scope can screw up the dependency tree for projects which import the BOM.

For a real example, take a look at the dependency tree of:

https://github.com/fabric8io/ipaas-quickstarts/tree/master/quickstart/cdi/camel-jetty

Notice many of the Arquillian and ShrinkWrap dependencies have their scopes overridden to 'compile' as a result of importing fabric8-project-bom-with-platform-deps. They should be 'test' scoped. 

Taking one ShrinkWrap dependency as an example:
```
$ mvn dependency:tree -Dincludes=org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api -Dverbose

[INFO] io.fabric8.quickstarts:cdi-camel-jetty:jar:2.3-SNAPSHOT
[INFO] +- io.fabric8:fabric8-arquillian:jar:2.2.139:test
[INFO] |  \- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-depchain:pom:2.2.2:compile (scope managed from test)
```
Maybe it's only worth doing [this](https://github.com/sundrio/sundrio/blob/master/maven-plugin/src/main/java/io/sundr/maven/GenerateBomMojo.java#L405), if the scope of the artifact being processed != compile ??

**Comment by jamesnetherton** [comment]
BTW my motive for raising this was that any fat-jar generating plugins will likely pick up unwated stuff. Which results in larger jar sizes, more stuff on the classpath etc.

**Comment by iocanel** [comment]
I don't mind doing so (having the scope only when its not compile). Do you want to send a PR, or you'd like me to quickfix it?

**Comment by jamesnetherton** [comment]
I'll submit a PR shortly.

Cheers.

**Comment by iocanel** [comment]
Added 2 commits:

- First one, retain the scope that has been explicitly specified on project artifacts.
- The second allows inheritance of the test scope from test only transitive dependencies.

In most case the later is desirable, but there can be very rare exceptions. For those exception the projects dependency management has priority over this, and of course the user can override stuff.

@jamesnetherton: What do you think? If you are ok with it, I can release asap. If not I can rollback.

**Comment by jamesnetherton** [comment]
Sounds good. I tested out those changes and it seems to have had the desired effect. 

If you can do a release, that'd be great.

**Comment by iocanel** [comment]
Cool, release is on its way!

**Comment by jamesnetherton** [comment]
Tested the new release and it all seems fine.

I'll close this now.
