### ISSUE TITLE
Generated code should not import its types

### ISSUE THREAD

**Issue by ericbottard** [sundrio/sundrio#81]
This can lead to ambiguity and thus compilation failure.

Here is an example with `generateBuilderPackage=true`, not sure if it also applies to runtime-dep (I guess it does) that also uses `@Inline` of `Bar`, so the problem may stem from the combination of all this.

For type `Foo`, `builderPackage="my.pkg"` you'll get:
```
import my.pkg.Function;
import io.Bar;

public class BarFoo extends FooFluentImpl<BarFoo> implements Bar<Foo>{

    private final FooBuilder builder;
    private final my.pkg.Function<Foo,Foo> function;

    public BarFoo(my.pkg.Function<Foo,Foo> function){
            super();this.builder=new FooBuilder(this);this.function=function;
    }
    public BarFoo(Foo item,my.pkg.Function<Foo,Foo> function){
            super(item);this.builder=new FooBuilder(this, item);this.function=function;
    }
    public BarFoo(Foo item){
            super(item);this.builder=new FooBuilder(this, item);this.function=new Function<Foo, Foo>() {
    public Foo apply(Foo item) {
        return item;
    }

```

Now this is all fine, until `Foo` is actually the name of a type of this project like ... `Function`.
Then the compiler complains that the constructors have the same erasure.

This is really a shame, as this could be fixed by just removing the import statements (as the framework types like `my.pkg.Function` are used with their fully qualified name throughout).

I hope this makes sense (and also that adding imports is an explicit choice of yours and that it can be removed, ie it's not the codegen library that tries to be smart :( )

**Comment by iocanel** [comment]
@ericbottard: Sorry for taking forever to reply!

The idea of generating the builder package is to eliminate any runtime dependency to this project (generate base classes instead of having a runtime dependency on them).

Will try to reproduce and fix the issue shortly.

**Comment by iocanel** [comment]
As of 0.40.0 we have the following changes:

- All Classes (included internal ones) are referenced by fully qualified name (I intend to exclude generated and user classes in the future, but I am not really sure).
- Classes like Predicate and Function have been dropped in favor of the `java.util.function` ones.

So, I think that these two changes should deal with the issue. I am closing, with apologies for the insanely long time it took. And we can reopen if these are not enough.
