### ISSUE TITLE
with* methods in FluentImpl should check for null parameter first

### ISSUE THREAD

**Issue by metacosm** [sundrio/sundrio#95]
Generated code for a `appendHeaders` Map property:
`public A withAppendHeaders(Map<String, String> appendHeaders) {
        if (this.appendHeaders == null) {
            this.appendHeaders = new LinkedHashMap();
        } else {
            this.appendHeaders.clear();
        }

        if (appendHeaders != null) {
            this.appendHeaders.putAll(appendHeaders);
        }

        return this;
    }`

If `appendHeaders` is `null`, `this.appendHeaders` should not be initialized. Also, it seems like the method could be simplified to:

`public A withAppendHeaders(Map<String, String> appendHeaders) {
        if(appendHeaders == null) {
            this.appendHeaders = null;
        } else {
            this.appendHeaders = new LinkedHashMap(appendHeaders);
        }
        
        return this;
    }`
which I believe would be functionally equivalent (unless there's a particular reason to avoid allocating a new LinkedHashMap) apart for the above case where given parameter is null.

**Comment by metacosm** [comment]
Thanks!

**Comment by metacosm** [comment]
Actually, this fix leads to a new issue as now the target field might not be initialized:
`public A addToLabels(String key,String value){
       if(key != null && value != null) {this.labels.put(key, value);} return (A)this;
}
public A addToLabels(Map<String,String> map){
       if(map != null) { this.labels.putAll(map);} return (A)this;
}`

In the code above, `this.labels` might be null so it needs to be lazily instantiated with something like:

`private Map<String,String> getLabels(boolean create) {
   if (create && this.labels == null) {
       this.labels = new LinkedHashMap<String, String>();
   } else {
       return this.labels;
   }
}`

and then calls to `this.labels` would need to be replaced by `getLabels(true)` where appropriate.

**Comment by metacosm** [comment]
@iocanel issue seems fixed on my side with these commits. Thanks!

**Comment by iocanel** [comment]
great! release incoming!
