### ISSUE TITLE
Inefficient bean validation

### ISSUE THREAD

**Issue by bartebor** [sundrio/sundrio#98]
Current validation implementation is very resource consuming, because it creates new validator object on each invocation in `snippets/validate.txt`. 
When builders are used frequently, validation becomes a major cpu hog scanning classpaths, unzipping JARs etc. We have such a case using fabric8io's kubernetes-client.

It would be much more efficient to reuse the same validation object as `javax.validation.Validation`'s documentation suggests. A static instance or user-provided factory would probably solve this problem (I do not know internal workings of generator, so I'm guessing).

**Comment by iocanel** [comment]
@bartebor: I'll have a look.

**Comment by bartebor** [comment]
@iocanel,  thanks for the fix :) 
When do you plan to make a release?

**Comment by iocanel** [comment]
@bartebor: It's been already released as part of 0.9.0.

**Comment by bartebor** [comment]
Ok, thanks - I just could not find new release here: https://github.com/sundrio/sundrio/releases
